const Map<String,String> ar ={
  'Select Stage':'اختار مرحله',
  'Select The Stage...':'اختار المرحله...',
  'Primary\nStage':'المرحلة\nالابتدائية',
  'Stage':'المرحلة',
  'Prep\nStage':'المرحلة\nالاعدادية',
  'Secondary\nStage':'المرحلة\nالثانوية',
  'Add Class':'اضافة فصل',
  'Enter The Class Name':'ادخل اسم الفصل',
  'Primary Stage':'المرحلة الابتدائية',
  'Save':'حفظ',
  'Delete':'حذف',
  'Edit Class':'تعديل اسم الفصل',
  'Add Name':'اضافة اسم الطالب',
  'Enter The Name':'ادخل اسم الطالب',
  'Edit Absence':'تعديل الغياب',
  'Exist':'حاضر',
  'Absent':'غائب',
  'Edit Name':'تعديل اسم الطالب',
  'Prep Stage':'المرحلة الاعدادية',
  'Secondary Stage':'المرحلة الثانوية',
  'Add Image\nFrom Camera':'اضافة صورة \n من الكاميرا',
  'Add Image\nFrom Gallery':'اضافة صورة \n من معرض الصور',
  'Email':'الإيميل',
  'Enter your Email':'ادخل الايميل',
  'Please Enter Your Email':'من فضلك ادخل الايميل',
  'User Name':'اسم المستخدم',
  'Please Enter Your Name':'من فضلك ادخل اسم المستخدم',
  'Enter your Name':'ادخل اسم المستخدم',
  'Password':'كلمة المرور',
  'Please Enter Your Password':'من فضلك ادخل كلمة المرور',
  'Enter your Password':'ادخل كلمة المرور',
  'LogIn':'تسجل الدخول',
  'SignUp':'انشاء حساب',
  'I don\'t have a account':'ليس لدي حساب' ,
  'The password is too  weak':'كلمة المرور ضعيفة جدا',
  'The account is already exist':'الحساب موجود بالفعل',
  'No user found for that email':'لا يوجد حساب لهذا الايميل',
  'Wrong password provided for that user':'كلمة المرور لهذا الحساب خاطئة',
  'Logout':'تسجيل الخروج',
  'Are You Sure To Delete The Class?':'هل انت متأكد من حذف الفصل؟',
  'Ok':'موافق',
  'Close':'غلق',
  'Are You Sure To Logout?':'هل انت متأكد من تسجيل الخروج؟',
};