const Map<String,String> en ={
    'Select Stage':'Select Stage',
    'Select The Stage...':'Select The Stage...',
    'Primary\nStage':'Primary\nStage',
    'Stage':'Stage',
    'Prep\nStage':'Prep\nStage',
    'Secondary\nStage':'Secondary\nStage',
    'Add Class':'Add Class',
    'Enter The Class Name':'Enter The Class Name',
    'Primary Stage':'Primary Stage',
    'Save':'Save',
    'Delete':'Delete',
    'Edit Class':'Edit Class',
    'Add Name':'Add Name',
    'Enter The Name':'Enter The Name',
    'Edit Absence':'Edit Absence',
    'Exist':'Exist',
    'Absent':'Absent',
    'Edit Name':'Edit Name',
    'Prep Stage':'Prep Stage',
    'Secondary Stage':'Secondary Stage',
    'Add Image\nFrom Camera':'Add Image\nFrom Camera',
    'Add Image\nFrom Gallery':'Add Image\nFrom Gallery',
    'Email':'Email',
    'Enter your Email':'Enter your Email',
    'Please Enter Your Email':'Please Enter Your Email',
    'User Name':'User Name',
    'Please Enter Your Name':'Please Enter Your Name',
    'Enter your Name':'Enter your Name',
    'Password':'Password',
    'Please Enter Your Password':'Please Enter Your Password',
    'Enter your Password':'Enter your Password',
    'LogIn':'LogIn',
    'SignUp':'SignUp',
    'I don\'t have a account':'I don\'t have a account' ,
    'The password is too  weak':'The password is too  weak',
    'The account is already exist':'The account is already exist',
    'No user found for that email':'No user found for that email',
    'Wrong password provided for that user':'Wrong password provided for that user',
    'Logout':'Logout',
    'Are You Sure To Delete The Class?':'Are You Sure To Delete The Class?',
    'Ok':'Ok',
    'Close':'Close',
    'Are You Sure To Logout?':'Are You Sure To Logout?',
    };